services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hi_interview
      POSTGRES_USER: hi
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - dbvolume:/var/lib/postgresql/data

volumes:
  dbvolume:
